### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by MrPowerMac** [Heholord/FalconStats#5]
I noticed this project doesn't have a license associated with it.
[By the Free Software Foundation's definition,](https://www.gnu.org/licenses/license-list.html#NoLicense) software without a license is not free. It looks like the intent is to have this be a free software project, based on the fact that you have been accepting code from a few contributors.

I suggest you add a suitable license to this repository, to clarify that the code is free software. [Choosealicense.com](https://choosealicense.com/) is a good resource for selecting a suitable license.

I personally recommend the [GNU GPL v3](https://choosealicense.com/licenses/gpl-3.0/).

**Comment by Heholord** [comment]
Thank you very much for this hint. I thought about the same thing in the morining but was to scared to look into the licence topic. I read a brief introduction to the GNU GPL Licence and i trust your recommendation.

**Comment by HermannBjorgvin** [comment]
MIT License is less limiting regarding dependencies, I don't consent to my code being GPLv3 licensed. Suggest MIT license or at least different licenses per script author

**Comment by ghost** [comment]
Throwing my hat in.  I agree this should be under the MIT license but won't that conflict with what the JS license is?  I know an MIT license can be in a GPL software but not vice versa.

**Comment by HermannBjorgvin** [comment]
A lot of these scripts use other programs like hddtemp or apcaccess to access statistics. I don't want to have to reject a good pull request because a script is dependent on a propriatery program for a UPS or a GPU for example.

"To be more specific, the doctrine is that a GPL program A is tightly coupled to another program B if it does not make sense to use A outside of B or B without A. In that specific case B should be GPL-licensed too. In other words, coding willingly a GPL wrapper around/for a proprietary program (or vice versa) is considered "cheating" the free software license."

**Comment by ghost** [comment]
You have a point and you won't hear any disagreements from here.  Side note:  I can't think of a use case for a GPU on these.  Perhaps a compute server?

**Comment by HermannBjorgvin** [comment]
homelab tensor flow rack maybe, maybe some ups requires a propriatery program to get statistics from it, maybe a user wants to get information from a propriatery database. I think the best license would be MIT and then have each script check if the user has the program it wants to query from installed, I don't think that would violate GPL since the code can run without the propriatery program installed.

**Comment by Heholord** [comment]
So should we license it to MIT?

**Comment by Heholord** [comment]
@HermannBjorgvin please close this issue if you agree to the current license

**Comment by HermannBjorgvin** [comment]
Yes I think this is good. Issue resolved from my viewpoint at least
